version: '3'
services:
  db:
    image: mongo:8.0
    container_name: db
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  express:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: express-server
    image: nosql2h24-pc-express:0.8
    ports:
      - "4444:4444"

    depends_on:
      - db
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
